// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/shaohsiung/memo/api/protobuf"
	"github.com/shaohsiung/memo/internal/memo"
	"github.com/shaohsiung/memo/internal/pkg/dbcontext"
)

// Injectors from wire.go:

func InitMemoServer(DSN string) (protobuf.MemoServer, error) {
	db := dbcontext.NewDB(DSN)
	repository := memo.NewRepository(db)
	memoServer := memo.NewServer(repository)
	return memoServer, nil
}
